repos:
  - repo: local
    hooks:
      - id: prevent-ios-runner-xcodeproj-update
        name: Prevent iOS Runner Xcodeproj Update
        entry: bash -c '[ "$(git diff --name-only --cached ios/Runner.xcodeproj/project.pbxproj)" == "" ] || { echo "Changes detected in ios/Runner.xcodeproj/project.pbxproj; committing aborted." >&2; exit 1; }'
        language: system
        stages: [pre-commit]
        types: [file]
