name: flows
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.0.5

dependencies:
  http: ^1.1.0
  markdown: ^7.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
