name: flows
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=1.16.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  logger: ^2.4.0
  markdown: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  test: ^1.21.0
