#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.1.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::rust2dart::IntoIntoDart;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_start_native_impl(
    port_: MessagePort,
    storage_path: impl Wire2Api<String> + UnwindSafe,
    portal_base_url: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "start_native",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || {
            let api_storage_path = storage_path.wire2api();
            let api_portal_base_url = portal_base_url.wire2api();
            move |task_callback| {
                start_native(
                    api_storage_path,
                    api_portal_base_url,
                    task_callback.stream_sink::<_, DomainMessage>(),
                )
            }
        },
    )
}
fn wire_get_my_stations_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, Vec<StationConfig>, _>(
        WrapInfo {
            debug_name: "get_my_stations",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| get_my_stations(),
    )
}
fn wire_authenticate_portal_impl(
    port_: MessagePort,
    email: impl Wire2Api<String> + UnwindSafe,
    password: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, Authenticated, _>(
        WrapInfo {
            debug_name: "authenticate_portal",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_email = email.wire2api();
            let api_password = password.wire2api();
            move |task_callback| authenticate_portal(api_email, api_password)
        },
    )
}
fn wire_add_or_update_station_in_portal_impl(
    port_: MessagePort,
    tokens: impl Wire2Api<Tokens> + UnwindSafe,
    station: impl Wire2Api<AddOrUpdatePortalStation> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, Option<u32>, _>(
        WrapInfo {
            debug_name: "add_or_update_station_in_portal",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_tokens = tokens.wire2api();
            let api_station = station.wire2api();
            move |task_callback| add_or_update_station_in_portal(api_tokens, api_station)
        },
    )
}
fn wire_configure_wifi_networks_impl(
    port_: MessagePort,
    device_id: impl Wire2Api<String> + UnwindSafe,
    config: impl Wire2Api<WifiNetworksConfig> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "configure_wifi_networks",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_device_id = device_id.wire2api();
            let api_config = config.wire2api();
            move |task_callback| configure_wifi_networks(api_device_id, api_config)
        },
    )
}
fn wire_configure_wifi_transmission_impl(
    port_: MessagePort,
    device_id: impl Wire2Api<String> + UnwindSafe,
    config: impl Wire2Api<WifiTransmissionConfig> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "configure_wifi_transmission",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_device_id = device_id.wire2api();
            let api_config = config.wire2api();
            move |task_callback| configure_wifi_transmission(api_device_id, api_config)
        },
    )
}
fn wire_configure_lora_transmission_impl(
    port_: MessagePort,
    device_id: impl Wire2Api<String> + UnwindSafe,
    config: impl Wire2Api<LoraTransmissionConfig> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "configure_lora_transmission",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_device_id = device_id.wire2api();
            let api_config = config.wire2api();
            move |task_callback| configure_lora_transmission(api_device_id, api_config)
        },
    )
}
fn wire_verify_lora_transmission_impl(
    port_: MessagePort,
    device_id: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "verify_lora_transmission",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_device_id = device_id.wire2api();
            move |task_callback| verify_lora_transmission(api_device_id)
        },
    )
}
fn wire_clear_calibration_impl(
    port_: MessagePort,
    device_id: impl Wire2Api<String> + UnwindSafe,
    module: impl Wire2Api<usize> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "clear_calibration",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_device_id = device_id.wire2api();
            let api_module = module.wire2api();
            move |task_callback| clear_calibration(api_device_id, api_module)
        },
    )
}
fn wire_calibrate_impl(
    port_: MessagePort,
    device_id: impl Wire2Api<String> + UnwindSafe,
    module: impl Wire2Api<usize> + UnwindSafe,
    data: impl Wire2Api<Vec<u8>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "calibrate",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_device_id = device_id.wire2api();
            let api_module = module.wire2api();
            let api_data = data.wire2api();
            move |task_callback| calibrate(api_device_id, api_module, api_data)
        },
    )
}
fn wire_validate_tokens_impl(port_: MessagePort, tokens: impl Wire2Api<Tokens> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, Authenticated, _>(
        WrapInfo {
            debug_name: "validate_tokens",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_tokens = tokens.wire2api();
            move |task_callback| validate_tokens(api_tokens)
        },
    )
}
fn wire_start_download_impl(
    port_: MessagePort,
    device_id: impl Wire2Api<String> + UnwindSafe,
    first: impl Wire2Api<Option<u64>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, TransferProgress, _>(
        WrapInfo {
            debug_name: "start_download",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_device_id = device_id.wire2api();
            let api_first = first.wire2api();
            move |task_callback| start_download(api_device_id, api_first)
        },
    )
}
fn wire_start_upload_impl(
    port_: MessagePort,
    device_id: impl Wire2Api<String> + UnwindSafe,
    tokens: impl Wire2Api<Tokens> + UnwindSafe,
    files: impl Wire2Api<Vec<RecordArchive>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, TransferProgress, _>(
        WrapInfo {
            debug_name: "start_upload",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_device_id = device_id.wire2api();
            let api_tokens = tokens.wire2api();
            let api_files = files.wire2api();
            move |task_callback| start_upload(api_device_id, api_tokens, api_files)
        },
    )
}
fn wire_cache_firmware_impl(
    port_: MessagePort,
    tokens: impl Wire2Api<Option<Tokens>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, FirmwareDownloadStatus, _>(
        WrapInfo {
            debug_name: "cache_firmware",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_tokens = tokens.wire2api();
            move |task_callback| cache_firmware(api_tokens)
        },
    )
}
fn wire_upgrade_station_impl(
    port_: MessagePort,
    device_id: impl Wire2Api<String> + UnwindSafe,
    firmware: impl Wire2Api<LocalFirmware> + UnwindSafe,
    swap: impl Wire2Api<bool> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, UpgradeProgress, _>(
        WrapInfo {
            debug_name: "upgrade_station",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_device_id = device_id.wire2api();
            let api_firmware = firmware.wire2api();
            let api_swap = swap.wire2api();
            move |task_callback| upgrade_station(api_device_id, api_firmware, api_swap)
        },
    )
}
fn wire_rust_release_mode_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, bool, _>(
        WrapInfo {
            debug_name: "rust_release_mode",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Result::<_, ()>::Ok(rust_release_mode()),
    )
}
fn wire_create_log_sink_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (), _>(
        WrapInfo {
            debug_name: "create_log_sink",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || move |task_callback| create_log_sink(task_callback.stream_sink::<_, String>()),
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<bool> for bool {
    fn wire2api(self) -> bool {
        self
    }
}

impl Wire2Api<i64> for i64 {
    fn wire2api(self) -> i64 {
        self
    }
}

impl Wire2Api<u32> for u32 {
    fn wire2api(self) -> u32 {
        self
    }
}
impl Wire2Api<u64> for u64 {
    fn wire2api(self) -> u64 {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

impl Wire2Api<usize> for usize {
    fn wire2api(self) -> usize {
        self
    }
}

// Section: impl IntoDart

impl support::IntoDart for Authenticated {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.email.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.tokens.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Authenticated {}
impl rust2dart::IntoIntoDart<Authenticated> for Authenticated {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for BatteryInfo {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.percentage.into_into_dart().into_dart(),
            self.voltage.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for BatteryInfo {}
impl rust2dart::IntoIntoDart<BatteryInfo> for BatteryInfo {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for DeviceCapabilities {
    fn into_dart(self) -> support::DartAbi {
        vec![self.udp.into_into_dart().into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for DeviceCapabilities {}
impl rust2dart::IntoIntoDart<DeviceCapabilities> for DeviceCapabilities {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for DomainMessage {
    fn into_dart(self) -> support::DartAbi {
        match self {
            Self::PreAccount => vec![0.into_dart()],
            Self::NearbyStations(field0) => {
                vec![1.into_dart(), field0.into_into_dart().into_dart()]
            }
            Self::StationRefreshed(field0, field1, field2) => vec![
                2.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_dart(),
                field2.into_into_dart().into_dart(),
            ],
            Self::UploadProgress(field0) => {
                vec![3.into_dart(), field0.into_into_dart().into_dart()]
            }
            Self::DownloadProgress(field0) => {
                vec![4.into_dart(), field0.into_into_dart().into_dart()]
            }
            Self::FirmwareDownloadStatus(field0) => {
                vec![5.into_dart(), field0.into_into_dart().into_dart()]
            }
            Self::UpgradeProgress(field0) => {
                vec![6.into_dart(), field0.into_into_dart().into_dart()]
            }
            Self::AvailableFirmware(field0) => {
                vec![7.into_dart(), field0.into_into_dart().into_dart()]
            }
            Self::RecordArchives(field0) => {
                vec![8.into_dart(), field0.into_into_dart().into_dart()]
            }
        }
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for DomainMessage {}
impl rust2dart::IntoIntoDart<DomainMessage> for DomainMessage {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for DownloadProgress {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.started.into_into_dart().into_dart(),
            self.completed.into_into_dart().into_dart(),
            self.total.into_into_dart().into_dart(),
            self.received.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for DownloadProgress {}
impl rust2dart::IntoIntoDart<DownloadProgress> for DownloadProgress {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for EphemeralConfig {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.transmission.into_dart(),
            self.networks.into_into_dart().into_dart(),
            self.lora.into_dart(),
            self.capabilities.into_into_dart().into_dart(),
            self.events.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for EphemeralConfig {}
impl rust2dart::IntoIntoDart<EphemeralConfig> for EphemeralConfig {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for FirmwareDownloadStatus {
    fn into_dart(self) -> support::DartAbi {
        match self {
            Self::Checking => vec![0.into_dart()],
            Self::Downloading(field0) => vec![1.into_dart(), field0.into_into_dart().into_dart()],
            Self::Offline => vec![2.into_dart()],
            Self::Completed => vec![3.into_dart()],
            Self::Failed => vec![4.into_dart()],
        }
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for FirmwareDownloadStatus {}
impl rust2dart::IntoIntoDart<FirmwareDownloadStatus> for FirmwareDownloadStatus {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for FirmwareInfo {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.label.into_into_dart().into_dart(),
            self.time.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for FirmwareInfo {}
impl rust2dart::IntoIntoDart<FirmwareInfo> for FirmwareInfo {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for LocalFirmware {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.id.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.time.into_into_dart().into_dart(),
            self.module.into_into_dart().into_dart(),
            self.profile.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for LocalFirmware {}
impl rust2dart::IntoIntoDart<LocalFirmware> for LocalFirmware {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for LoraBand {
    fn into_dart(self) -> support::DartAbi {
        match self {
            Self::F915Mhz => 0,
            Self::F868Mhz => 1,
        }
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for LoraBand {}
impl rust2dart::IntoIntoDart<LoraBand> for LoraBand {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for LoraConfig {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.available.into_into_dart().into_dart(),
            self.band.into_into_dart().into_dart(),
            self.device_eui.into_into_dart().into_dart(),
            self.app_key.into_into_dart().into_dart(),
            self.join_eui.into_into_dart().into_dart(),
            self.device_address.into_into_dart().into_dart(),
            self.network_session_key.into_into_dart().into_dart(),
            self.app_session_key.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for LoraConfig {}
impl rust2dart::IntoIntoDart<LoraConfig> for LoraConfig {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for ModuleConfig {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.position.into_into_dart().into_dart(),
            self.module_id.into_into_dart().into_dart(),
            self.key.into_into_dart().into_dart(),
            self.sensors.into_into_dart().into_dart(),
            self.configuration.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for ModuleConfig {}
impl rust2dart::IntoIntoDart<ModuleConfig> for ModuleConfig {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for NearbyStation {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.device_id.into_into_dart().into_dart(),
            self.busy.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for NearbyStation {}
impl rust2dart::IntoIntoDart<NearbyStation> for NearbyStation {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for NetworkConfig {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.index.into_into_dart().into_dart(),
            self.ssid.into_into_dart().into_dart(),
            self.preferred.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for NetworkConfig {}
impl rust2dart::IntoIntoDart<NetworkConfig> for NetworkConfig {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for PortalError {
    fn into_dart(self) -> support::DartAbi {
        match self {
            Self::Authentication => vec![0.into_dart()],
            Self::Other(field0) => vec![1.into_dart(), field0.into_into_dart().into_dart()],
        }
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for PortalError {}
impl rust2dart::IntoIntoDart<PortalError> for PortalError {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for RecordArchive {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.device_id.into_into_dart().into_dart(),
            self.path.into_into_dart().into_dart(),
            self.head.into_into_dart().into_dart(),
            self.tail.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for RecordArchive {}
impl rust2dart::IntoIntoDart<RecordArchive> for RecordArchive {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for SensorConfig {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.number.into_into_dart().into_dart(),
            self.key.into_into_dart().into_dart(),
            self.full_key.into_into_dart().into_dart(),
            self.calibrated_uom.into_into_dart().into_dart(),
            self.uncalibrated_uom.into_into_dart().into_dart(),
            self.value.into_dart(),
            self.previous_value.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for SensorConfig {}
impl rust2dart::IntoIntoDart<SensorConfig> for SensorConfig {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for SensorValue {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.time.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.uncalibrated.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for SensorValue {}
impl rust2dart::IntoIntoDart<SensorValue> for SensorValue {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for SolarInfo {
    fn into_dart(self) -> support::DartAbi {
        vec![self.voltage.into_into_dart().into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for SolarInfo {}
impl rust2dart::IntoIntoDart<SolarInfo> for SolarInfo {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for StationConfig {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.device_id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.firmware.into_into_dart().into_dart(),
            self.last_seen.into_into_dart().into_dart(),
            self.meta.into_into_dart().into_dart(),
            self.data.into_into_dart().into_dart(),
            self.battery.into_into_dart().into_dart(),
            self.solar.into_into_dart().into_dart(),
            self.modules.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for StationConfig {}
impl rust2dart::IntoIntoDart<StationConfig> for StationConfig {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for StreamInfo {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.size.into_into_dart().into_dart(),
            self.records.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for StreamInfo {}
impl rust2dart::IntoIntoDart<StreamInfo> for StreamInfo {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for Tokens {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.token.into_into_dart().into_dart(),
            self.transmission.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Tokens {}
impl rust2dart::IntoIntoDart<Tokens> for Tokens {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for TransferProgress {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.device_id.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for TransferProgress {}
impl rust2dart::IntoIntoDart<TransferProgress> for TransferProgress {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for TransferStatus {
    fn into_dart(self) -> support::DartAbi {
        match self {
            Self::Starting => vec![0.into_dart()],
            Self::Downloading(field0) => vec![1.into_dart(), field0.into_into_dart().into_dart()],
            Self::Uploading(field0) => vec![2.into_dart(), field0.into_into_dart().into_dart()],
            Self::Processing => vec![3.into_dart()],
            Self::Completed => vec![4.into_dart()],
            Self::Failed => vec![5.into_dart()],
        }
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for TransferStatus {}
impl rust2dart::IntoIntoDart<TransferStatus> for TransferStatus {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for TransmissionConfig {
    fn into_dart(self) -> support::DartAbi {
        vec![self.enabled.into_into_dart().into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for TransmissionConfig {}
impl rust2dart::IntoIntoDart<TransmissionConfig> for TransmissionConfig {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for TransmissionToken {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.token.into_into_dart().into_dart(),
            self.url.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for TransmissionToken {}
impl rust2dart::IntoIntoDart<TransmissionToken> for TransmissionToken {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for UpgradeProgress {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.device_id.into_into_dart().into_dart(),
            self.firmware_id.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for UpgradeProgress {}
impl rust2dart::IntoIntoDart<UpgradeProgress> for UpgradeProgress {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for UpgradeStatus {
    fn into_dart(self) -> support::DartAbi {
        match self {
            Self::Starting => vec![0.into_dart()],
            Self::Uploading(field0) => vec![1.into_dart(), field0.into_into_dart().into_dart()],
            Self::Restarting => vec![2.into_dart()],
            Self::Completed => vec![3.into_dart()],
            Self::Failed => vec![4.into_dart()],
        }
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for UpgradeStatus {}
impl rust2dart::IntoIntoDart<UpgradeStatus> for UpgradeStatus {
    fn into_into_dart(self) -> Self {
        self
    }
}

impl support::IntoDart for UploadProgress {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.bytes_uploaded.into_into_dart().into_dart(),
            self.total_bytes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for UploadProgress {}
impl rust2dart::IntoIntoDart<UploadProgress> for UploadProgress {
    fn into_into_dart(self) -> Self {
        self
    }
}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
#[path = "bridge_generated.web.rs"]
mod web;
#[cfg(target_family = "wasm")]
pub use web::*;

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
